version: 2.1
orbs:
  node: circleci/node@2.0.2
  docker: circleci/docker@1.0.1
  aws-cli: circleci/aws-cli@1.0.0
jobs:
  aws-setup:
    executor: aws-cli/default
    steps:
#      - checkout
      - aws-cli/install
      - aws-cli/setup
      - run: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
#  docker-publish:
#    executor: docker/docker
#    steps:
#      - checkout
#      - docker/publish:
#          image: 119074797651.dkr.ecr.us-west-2.amazonaws.com/docker-multi
#          registry: 119074797651.dkr.ecr.us-west-2.amazonaws.com/docker-multi
workflows:
#  version: 2
  test_and_deploy:
    jobs:
      - node/test
      - aws-setup:
          requires:
            - node/test
#      - aws-cli/setup:
#          requires:
#            - aws-cli/install
#      - aws-login:
#          requires:
#            - node/test
#            - aws-cli/setup
#      - docker-publish:
#          requires:
#            - aws-login
